services:
  web:
    build: .
    # command: bash -c "service cron start && python manage.py runserver 0.0.0.0:8000"
    command: ["/usr/bin/supervisord"]
    container_name: mchl-py
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "8014:8000"


